lib/jelix/utils/jMailer.class.php
In bundled phpMailer, ReplyTo is now Reply-to (see class.phpmailer.php on line 784)
=> jMailer: fix for ReplyTo meta in tpl

lib/jelix-scripts/commands/initadmin.cmd.php
Since masteradmin do not require jauth, jAuth is not installed anymore and error occurs when trying to modify the auth plugin's config file.
This is a quick fix, maybe we should introduce a switch like "-nojauth" in the command, set to false by default.
=> jelix-scripts: initadmin doesn't work anymore

lib/jelix-legacy/plugins/db/pgsql/pgsql.dbconnection.php
"Service" is the PostgreSQL way to store database connection credentials in a file : http://www.postgresql.org/docs/9.1/static/libpq-pgservice.html
If given, no need to add host, user, database, port and password to the connection string. Instead, only pass service
=> jDb - Allow to use a PostgreSQL service for connection

lib/jelix-www/js/jforms/htmleditors/wymeditor_basic.js, lib/jelix-www/js/jforms/htmleditors/wymeditor_default.js
Because of this code `c._options.jQueryPath||WYMeditor.computeJqueryPath()`, it's necessary to pass all the jQuery path or nothing.
=> Update WYMeditor jQueryPath

lib/jelix/core/response/jResponseBinary.class.php
Useful if you serve inline media (pdf, image, video) and want a pretty, url independant, filename when users click "save as"
=> jResponseBinary: should include filename for inline disposition

lib/jelix-tests/classes/command.php
class jelix_TextUI_Command calls a showMessage() method when there are no tests in a module or in the app, but this method didn't exist.
=> add missing method showMessage() in class jelix_TextUI_Command

lib/jelix/plugins/db/pgsql/pgsql.dbtools.php
In PGSQL metadata, the default value is provided as SQL code:
* pg_catalog.concat((date_part('year'::text, now()) + (1)::double precision), 'TVX', to_char(nextval('technique.avi_travaux3_id_seq'::regclass), 'FM09999'::text))
* 'Mairie Avignon'::text
* 84007
Except for a nextval, the default value as to be evaluated if we want to display the default value
=> [BUGFIX] Evaluate default value from pgsql

lib/jelix/plugins/htmlresponse/debugbar/debugbar.css
missing some units so the debugbar could not be positioned on the right
also moved prefixed properties to use standard ones as default
=> debugbar: fix some missing units and move prefixed properties in CSS

lib/jelix/core/request/jClassicRequest.class.php
for DELETE requests for example, body may be null, and array_merge excepts arrays as parameters
=> jClassicRequest: data in request's body may be null fix

lib/jelix/dao/jDaoFactoryBase.class.php, lib/jelix/db/jDbPDOConnection.class.php
In 1.6.14, doing a query with an ORDER clause return you something like this :
`SELECT [table].[nameField] AS [name] FROM [table] AS [table] ORDER BY table.nameField`. 
But as you can see, the field name has an alias set in the DAO. So it's this alias that should be used for the ORDER clause too. With my edits, the final query looks like this :
`SELECT [table].[nameField] AS [name] FROM [table] AS [table] ORDER BY name`.
This change is necessary for the limitQuery to work, as it use multiple select with the ORDER clause.
Before the changes with ORDER clause : 
```
SELECT TOP 10 * FROM
(SELECT TOP 10 * FROM 
(SELECT TOP 10 [table].[nameField] AS [name],
FROM [table] AS [table]
ORDER BY table.nameField ASC)
AS inner_tbl  ORDER BY table.nameField DESC)
AS outer_tbl  ORDER BY table.nameField …
```
=> Allow limitQuery for sqlSrv and Order clause update

lib/jelix/db/jDbPDOConnection.class.php
Dans un fichier de DAO, une méthode déclaré en XML de type "selectfirst" contenant une clause `<order>` génère une requête SQL erronée pour une base de données SQLSRV.
`[42000]	SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The multi-part identifier "table2.date" could not be bound.`
Exemple de requête SQL générée à l'heure actuelle : 
<pre><code>
SELECT TOP 1 * FROM (
SELECT TOP 1 * FROM (
SELECT TOP 1
[table1].[numero] as [num1],
[table2].[numero] as [num2],
[table3].[numero] as [num3] 
FROM [table1] AS [table1] 
LEFT JOIN [table2] AS [table2] ON ( [table1].[num_table2]=[table2].[numero]) 
LEFT JOIN [table3] AS [table3] ON ( [table1].[num_table3]=[table3].[numero]) 
ORDER BY [table2].[date] asc) 
AS inner_tbl  ORDER BY <b>[table2].[date]</b> DESC) 
AS outer_tbl …
=> Correction d'un bug si une clause ORDER existe

lib/jelix/core/defaultconfig.ini.php
There is a bug in latest 1.6 version: js files for localizing datepicker are inverted. This PR fixes it.
=> Fix: js files for localizing datepicker were inverted

build/lib/jCmdUtils.class.php, lib/jelix/utils/jCmdUtils.class.php
There are 2 deprecation warnings in latest 1.6.29 when using jCmdUtils:
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /.../lib/jelix/utils/jCmdUtils.class.php on line 58
> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /.../lib/jelix/utils/jCmdUtils.class.php on line 55
This PR fixes it.
=> Remove warning from jCmdUtils in PHP 7.4

lib/jelix-admin-modules/jacl2db_admin/controllers/groups.classic.php, lib/jelix-modules/jacl2db/classes/jAcl2DbAdminUIManager.class.php, lib/jelix-modules/jacl2db/daos/jacl2rights.dao.xml, lib/jelix/core/defaultconfig.ini.php
Some rights have now the possibility to be hidden.
To do so, define a jacl2 section in localconfig.ini.php with a property `hiddenRights` containing the id of the rights to hide and a property `hideRights` set to `on` or `off` to hide the rights or not.
Example: 
```
[jacl2]
hiddenRights[] = auth.users.view
hiddenRights[] = auth.users.password.change
hideRights = on
```
The value of the hiddenRights won't be changed once they are hidden.
=> adding possibility to hide some rights to the admins

lib/jelix/auth/jAuth.class.php
Currently the persistant cookie name sent to the browser is inconsistent between login and logout.
That prevents people from logging out when they have a persistant cookie!!
This PR fixes it.
=> Fix logout with persistant cookie

lib/Jelix/Core/App.php
As described by PHPStan, the Jelix App Core class magic static method description does not contain the output.
https://phpstan.org/writing-php-code/phpdocs-basics#magic-methods
Needed by Lizmap to fix PHPStan errors https://github.com/3liz/lizmap-web-client/pull/3118
=> [DocString] Jelix App Core class magic static method

lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php
A new option `session_role` for pgsql connection profile to define the session role.
=> New option for pgsql to set session role

lib/jelix/core-modules/jelix/Command/MailerTest.php
while testing mail command in lwc 
`php lizmap/console.php mailer:test mymail@tld.fr `
Got a php Warning
`PHP Warning:  Attempt to read property "defaultResponseType" on null in /srv/lzm/lizmap/vendor/jelix/jelix/lib/jelix/core/selector/jSelectorTpl.class.php `
From https://github.com/jelix/jelix/blob/ef1702521cff3faa19d9da088e7af9db1c533891/lib/jelix/core-modules/jelix/Command/MailerTest.php#L73
Because in a Command "context" the request is unset ? 
https://github.com/jelix/jelix/blob/ef1702521cff3faa19d9da088e7af9db1c533891/lib/jelix/core/selector/jSelectorTpl.class.php#L47
The PR explicitly declare the template as html, but i wonder if a better solution can be done
=> explicit template format in mailTest command

lib/jelix-modules/jacl2db/Command/Acl2/RightsList.php
Add an empty cell for anonymous group in ` acl2:list` command
From 
to
=> fix Acl2 cmd list table display

lib/jelix/core/response/jResponseBinary.class.php
Fixes: `strlen(): Argument #1 ($str) must be of type string, Closure given lib/jelix/core/response/jResponseBinary.class.php	128`
=> jResponseBinary accepts callable content: strlen is not usable

lib/jelix/db/jDbColumn.class.php, lib/jelix/db/jDbTools.class.php, lib/jelix/db/tools/jDbPgsqlTools.php, lib/jelix/plugins/db/pgsql/pgsql.dbschema.php, testapp/docker-compose.yml, testapp/docker-conf/phpfpm/appctl.sh, testapp/modules/jelix_tests/install/install.pgsql.sql, testapp/tests-jelix/jelix/db/jdbschema_pgsqlTest.php
Ticket reference #405
NOTES:
- support is, for now, only for **PostgreSQL**
- following pgsql [doc](https://www.postgresql.org/docs/13/catalog-pg-attribute.html),  `attgenerated` return zero byte ('') if column is not generated, otherwise 's'. Since more value could be added in the future, I would consider as "generated columns" all columns that have `attgenerated != ''`. In fact, `attgenerated = 's' ` could be too restrictive and I would include all generated column, no matter their type.
- with "support" I mean that jelix can detect if a pgsql column is generated or not, but there is no dedicated method, for now, to CREATE generated columns. I'll let this feature for a separated PR.
=> [Feature] Add support for generated columns

lib/jelix/forms/controls/jFormsControlHtmlEditor.class.php, lib/jelix/forms/controls/jFormsControlInput.class.php, lib/jelix/forms/controls/jFormsControlTextarea.class.php, lib/jelix/forms/controls/jFormsControlWikiEditor.class.php, lib/jelix/forms/jFormsCompiler_jf_1_0.class.php, lib/jelix/forms/jFormsCompiler_jf_1_1.class.php, lib/jelix/plugins/formwidget/htmleditor_html/htmleditor_html.formwidget.php, lib/jelix/plugins/formwidget/input_html/input_html.formwidget.php, lib/jelix/plugins/formwidget/textarea_html/textarea_html.formwidget.php, lib/jelix/plugins/formwidget/wikieditor_html/wikieditor_html.formwidget.php, testapp/modules/testapp/forms/sample.form.xml, testapp/modules/testapp/locales/en_US/sample.UTF-8.properties
Add placeholder  in `textarea`/`input `controls (textarea, input, wikieditor, htmleditor)
As label :  locale can be used
=> Add HTML Placeholder for input/texteara controls
